INSERT INTO ROOM (BEAMERPRESENT, BUILDING, ROOM_NUMBER, SEATS) VALUES (TRUE, 'A', 101, 45);
INSERT INTO ROOM (BEAMERPRESENT, BUILDING, ROOM_NUMBER, SEATS) VALUES (FALSE, 'A', 102, 30);
INSERT INTO ROOM (BEAMERPRESENT, BUILDING, ROOM_NUMBER, SEATS) VALUES (TRUE, 'A', 103, 40);

INSERT INTO COURSE (FIELD_OF_STUDY, LECTURER, NUMBER, TITLE) VALUES ('I', 'Anft', 148, 'Internet-Anwendungsarchitektur');

INSERT INTO Bug (TITLE, DESCRIPTION, STATE, AUTOR, DEVELOPER, LASTUPDATEDATE, CREATIONDATE)
VALUES ('title', 'description', 'Angelegt', 1, 1, '02.01.2015', '01.01.2015');
INSERT INTO USER (EMAIL, FIRSTNAME, LASTNAME, PASSWORD) VALUES ('otto-wagner@gmx.net', 'Otto', 'Wagner', 'test');
